language: python
python:
  - "2.7"
  - "3.4"
# command to install dependencies
install:
  - pip install .
  - pip install tox
  - pip install codecov
# command to run tests
script: tox
  - coverage run tests.py

after_success:
	- codecov
	